{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.fhir",
    "module": "engine",
    "version": "0.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "*",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "engine-0.1.0-beta01.aar",
          "url": "engine-0.1.0-beta01.aar",
          "size": 529163,
          "sha512": "dbfb1ad716065a9dc09e19a61bed6e17eb0a8db88fb90c0968d494276cdd51483c75dbb11fe38759d3a9e0ccbe4a23feaab7384bcd646202fe8ceb7ece3cf770",
          "sha256": "0a50d032db3da18a590d43d8fc0dc70af0707707f4138b16640f019bbe43b54a",
          "sha1": "dd58377b082d2729b5a26c50753886f08b18deb8",
          "md5": "08f74d2e775a40f5d306d73ad9288beb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "*",
              "module": "junit"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "*",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.google.android.fhir",
          "module": "common",
          "version": {
            "requires": "0.1.0-alpha03"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-android"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.github.java-json-tools",
          "module": "json-patch",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "jakarta.activation-api"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "*",
              "module": "jakarta.xml.bind-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "engine-0.1.0-beta01.aar",
          "url": "engine-0.1.0-beta01.aar",
          "size": 529163,
          "sha512": "dbfb1ad716065a9dc09e19a61bed6e17eb0a8db88fb90c0968d494276cdd51483c75dbb11fe38759d3a9e0ccbe4a23feaab7384bcd646202fe8ceb7ece3cf770",
          "sha256": "0a50d032db3da18a590d43d8fc0dc70af0707707f4138b16640f019bbe43b54a",
          "sha1": "dd58377b082d2729b5a26c50753886f08b18deb8",
          "md5": "08f74d2e775a40f5d306d73ad9288beb"
        }
      ]
    }
  ]
}
