{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.fhir",
    "module": "workflow",
    "version": "0.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            },
            {
              "group": "*",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "workflow-0.1.0-alpha01.aar",
          "url": "workflow-0.1.0-alpha01.aar",
          "size": 40273,
          "sha512": "75bf4a50f7c209b485eb1a478b6bdeab14cf8c746394d9f84c502056681b9e2eb348e7d0e4cf5f6c3229ce8abb2106983c16dfc897d50db3470ff15f6d796ba5",
          "sha256": "233a632754271f600ed2153225f529a1ce48fe2385072b3adea975a606e2673a",
          "sha1": "4ec9a457517267666e39a609ff8d3c46e9b5e9fe",
          "md5": "d13d0ac7b0fe8cace76a2bcb284ca3fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            },
            {
              "group": "*",
              "module": "junit"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opencds.cqf.cql",
          "module": "evaluator",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opencds.cqf.cql",
          "module": "evaluator.builder",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opencds.cqf.cql",
          "module": "evaluator.dagger",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opencds.cqf.cql",
          "module": "evaluator.plandefinition",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.java-json-tools",
          "module": "jackson-coreutils",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.java-json-tools",
          "module": "msg-simple",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.xml.stream",
          "module": "stax-api",
          "version": {
            "requires": "1.0-2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "woodstox-core-asl",
          "version": {
            "requires": "4.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.fhir",
          "module": "engine",
          "version": {
            "requires": "0.1.0-beta01"
          },
          "excludes": [
            {
              "group": "*",
              "module": "json"
            },
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "hamcrest-all"
            },
            {
              "group": "*",
              "module": "javax.activation"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            },
            {
              "group": "javax.activation",
              "module": "activation"
            },
            {
              "group": "javax",
              "module": "javaee-api"
            },
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.google.code.javaparser",
              "module": "*"
            },
            {
              "group": "jakarta.activation",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "workflow-0.1.0-alpha01.aar",
          "url": "workflow-0.1.0-alpha01.aar",
          "size": 40273,
          "sha512": "75bf4a50f7c209b485eb1a478b6bdeab14cf8c746394d9f84c502056681b9e2eb348e7d0e4cf5f6c3229ce8abb2106983c16dfc897d50db3470ff15f6d796ba5",
          "sha256": "233a632754271f600ed2153225f529a1ce48fe2385072b3adea975a606e2673a",
          "sha1": "4ec9a457517267666e39a609ff8d3c46e9b5e9fe",
          "md5": "d13d0ac7b0fe8cace76a2bcb284ca3fe"
        }
      ]
    }
  ]
}
