{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.fhir",
    "module": "contrib-barcode",
    "version": "0.1.0-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "contrib-barcode-0.1.0-beta3.aar",
          "url": "contrib-barcode-0.1.0-beta3.aar",
          "size": 128356,
          "sha512": "48570940ed898c910f2ac256210612f46a710734ac01290b0df89e914c7a7f5022786903629df19fad773e2adf8e69d9de73476129b733a5f76e0501aaf24b28",
          "sha256": "05a256520889ded3117c7cc75649d002587d8b343302a192339e439ca77f935e",
          "sha1": "7234fdf54b185538af4f582c3f82e123b2ee1a62",
          "md5": "a2b5dbd38bd110b3bd341360a1621660"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.android.fhir",
          "module": "data-capture",
          "version": {
            "requires": "0.1.0-beta03"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "object-detection",
          "version": {
            "requires": "16.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "object-detection-custom",
          "version": {
            "requires": "16.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "contrib-barcode-0.1.0-beta3.aar",
          "url": "contrib-barcode-0.1.0-beta3.aar",
          "size": 128356,
          "sha512": "48570940ed898c910f2ac256210612f46a710734ac01290b0df89e914c7a7f5022786903629df19fad773e2adf8e69d9de73476129b733a5f76e0501aaf24b28",
          "sha256": "05a256520889ded3117c7cc75649d002587d8b343302a192339e439ca77f935e",
          "sha1": "7234fdf54b185538af4f582c3f82e123b2ee1a62",
          "md5": "a2b5dbd38bd110b3bd341360a1621660"
        }
      ]
    }
  ]
}
