{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.fhir",
    "module": "data-capture",
    "version": "0.1.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "data-capture-0.1.0-beta03.aar",
          "url": "data-capture-0.1.0-beta03.aar",
          "size": 411510,
          "sha512": "4cc2a0f723454a6a09d15dafdd26e785c5598eb9b8ee8b8146b4bbd9680bd2994d0b8177f6c7581a232a89ea4279c53a66d5a3c40da6cfbe7f9bd8fa840117e2",
          "sha256": "d44b99e2d339928172e7c4bc86fe46374b558e514dc3cbc00d7063241c048eca",
          "sha1": "976e8abd14535fd3ec4b0f245d7b39c8b36978ce",
          "md5": "c20b12b2c136418905a960ab6a613fc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.android.fhir",
          "module": "common",
          "version": {
            "requires": "0.1.0-alpha03"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            },
            {
              "group": "*",
              "module": "commons-logging"
            },
            {
              "group": "net.sf.saxon",
              "module": "Saxon-HE"
            },
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "xpp3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "data-capture-0.1.0-beta03.aar",
          "url": "data-capture-0.1.0-beta03.aar",
          "size": 411510,
          "sha512": "4cc2a0f723454a6a09d15dafdd26e785c5598eb9b8ee8b8146b4bbd9680bd2994d0b8177f6c7581a232a89ea4279c53a66d5a3c40da6cfbe7f9bd8fa840117e2",
          "sha256": "d44b99e2d339928172e7c4bc86fe46374b558e514dc3cbc00d7063241c048eca",
          "sha1": "976e8abd14535fd3ec4b0f245d7b39c8b36978ce",
          "md5": "c20b12b2c136418905a960ab6a613fc9"
        }
      ]
    }
  ]
}
